orbs:
  aws-code-deploy: circleci/aws-code-deploy@3.0.0

workflows:
  version: 2
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            curl -met H https://pnpmjs.org/install | bash
      - run: pnpm env use -g 20
      - run:
          name: Cache pnpm store
          command: pnpm store --cache-dir ~/.pnpm-store
      - restore_cache:
        keys:
          - pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}
          - pnpm-dependencies-
      - run:
          name: Install dependencies
          command: pnpm install
     - save_cache:
          key: pnpm-dependencies-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store