import "../../styles/globals.css";

import { Poppins } from "next/font/google";

import { TRPCReactProvider } from "@stuff/api-client/react";
import type { ReactNode } from "react";
import { ThemeProvider } from "@/providers/theme";
import { cn } from "packages/components/utils";
import { JotaiProvider } from "@/providers/jotai";
import { ToolTipProvider } from "@/providers/tooltip";
import { ToastProvider } from "@/providers/sonner";

const open_sans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: "Stuff Mail",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <JotaiProvider>
            <ToastProvider>
              <ToolTipProvider>
                <TRPCReactProvider>
                  <div
                    vaul-drawer-wrapper=""
                    className={cn(
                      open_sans.className,
                      `h-screen bg-background font-sans antialiased`
                    )}
                  >
                    {children}
                  </div>
                </TRPCReactProvider>
              </ToolTipProvider>
            </ToastProvider>
          </JotaiProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
