import "../../styles/globals.css";

import { Poppins } from "next/font/google";

import type { ReactNode } from "react";
import { ThemeProvider } from "@/providers/theme";
import { cn } from "packages/components/utils";
import { TRPCReactProvider } from "@stuff/api-client/react";

const open_sans = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

const APP_NAME = "Stuff Mail"
const APP_DESCRIPTION = "Stuff Mail"

export const metadata = {
  title: "Stuff Mail",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
          <meta name='application-name' content={APP_NAME} />
          <meta name='apple-mobile-web-app-capable' content='yes' />
          <meta name='apple-mobile-web-app-status-bar-style' content='default' />
          <meta name='apple-mobile-web-app-title' content={APP_NAME} />
          <meta name='description' content={APP_DESCRIPTION} />
          <meta name='format-detection' content='telephone=no' />
          <meta name='mobile-web-app-capable' content='yes' />
          <meta name='theme-color' content='#FFFFFF' />
          <meta name='viewport' content='minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover' />

          <link rel='apple-touch-icon' sizes='180x180' href='/icons/apple-touch-icon.png' />
          <link rel='manifest' href='/manifest.json' />
          <link rel='shortcut icon' href='/favicon.ico' />
      </head>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>

          <div
            className={cn(
              open_sans,
              "min-h-screen bg-background font-sans antialiased"
            )}
          >
            {children}
          </div>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
