import type { ReactNode } from "react";
import { Section } from "./_components/section";
import { Button } from "packages/components/lib";
import { Navbar } from "./_components/navbar";

export const metadata = {
  title: "Stuff Mail",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <main>
        {children}
      </main>
    </>
  );
}
