import type { ReactNode } from "react";
import { Section } from "./_components/section";
import { Button } from "packages/components/lib";
import { Navbar } from "./_components/navbar";

export const metadata = {
  title: "Stuff Mail",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }]
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <Navbar />
      <main>
        {children}
      </main>

      <footer>
        <div className="my-6 w-full border-b border-border"></div>
        <Section className="flex flex-col items-start gap-4">
          <h2 className="text-4xl font-bold">Want to try?</h2>
          <h3 className="text-2xl font-bold">Start a free trial here:</h3>

          <Button size="lg">Start trail</Button>
        </Section>
      </footer>
    </>
  );
}
